version: '3.8'
services:
  receipt-service:
    build: .
    ports:
      - "8083:8083"
    volumes:
      - .:/app
    environment:
      app.name: ReceiptService
    networks:
      - local-sub-net



networks:
  local-sub-net:
    driver: bridge
